name: neural_predictor
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  image: ^2.1.12
  hex: ^0.1.2
  perceptron:
    path: '../perceptron'

dev_dependencies:
  pedantic: ^1.8.0
